const constant = {
  // Error codes

  SUCCESS_STATUS_CODE: 200,
  CREATED_STATUS_CODE: 201,
  CREATE_STATUS_CODE: 201,
  VALIDATION_STATUS_CODE: 400,
  NOT_FOUND_STATUS_CODE: 404,
  SOMETHING_WENT_WRONG_STATUS_CODE: 500,
  FIREBASE_FAILED: 501,
  ALREADY_EXIT_STATUS_CODE: 409,
  PERMISSION_ERROR_STATUS_CODE: 403,
  ALREADY_EXIST_STATUS_CODE: 409,
  UNAUTHORIZED_CODE: 401,
  RECORD_NOT_FOUND_STATUS_CODE: 404,
  ACCESS_PERMISSION_CODE: 405,

  // Error messages
  ALREADY_EXIST_ERROR: "Already exists error",
  SUCCESS: "success",
  REGISTER_SUCCESS: "register successful",
  LOGIN_SUCCESS: "login successful",
  FIREBASE_FAILED_ERROR: "firebase_failed",
  PERMISSION_ERROR: "permission_error",
  PERMISSION_ERROR_DESCRIPTION:
    "You do not have permission to perform this action.",
  VALIDATION_TYPE_ERROR: "validationError",
  NOT_FOUND_ERROR: "Not Found",
  NOT_FOUND: "Not Found",
  RECORD_NOT_FOUND: "Record not found.",
  USER_NOT_FOUND: "User not found.",
  SOMETHING_WENT_WRONG_TYPE: "internal_issue",
  SOMETHING_WENT_WRONG: "Something wrong. Please try again",
  ACCOUNT_EXIST_ERROR: "account_exist",
  EMAIL_EXIST_ERROR: "Email already exists.",
  USERNAME_EXIST_ERROR: "Username already taken please choose another.",
  TOKEN_INVALID_ERROR: "verification_failed",
  TOKEN_REQUIRED_ERROR: "missing_token",
  TOKEN_EXPIRED: "Session is expired",
  INVALID_TOKEN: "Invalid token",
  TOKEN_VALIDATION: "Token is required",
  TOKEN_EXPIRED_ERROR: "sessionExpired",
  INVALID_DEVICE_TYPE: "Invalid device type.",
  INVALID_TYPE: "Invalid type",
  INACTIVE_USER: "Your profile was inactive.",
  INACTIVE_USER_ERROR: "inactive_user_error",
  NO_USERS_FOUND: "User not found.",
  EMAIL_NOT_VERIFIED: "Your email is not verified yet please verify first",

  WRONG_OTP: "wrong_otp",
  VERIFY_OTP: "OTP verified",
  WRONG_OTP_MSG: "Sorry! code was mismatch",
  NOTFOUND_OTP_MSG: "code is not valid",
  OTP_REQUIRED: "OTP required.",
  WRONG_CREDENTIALS_TYPE: "invalid_grant",
  WRONG_CREDENTIALS: "Invalid user credentials",
  WRONG_PASSWORD: "Wrong password",
  SAME_PASSWORD: "Old password and new password can not be same",
  USER_ID_NOT_EXIST: "User id not Exist.",
  UNSUBSCRIBE: "User has been unsubscribed Successfully",
  USER_LOGOUT: "logout Successfully",
  REFRESH_TOKEN_INVALID_ERROR: "refresh_verification_failed",
  TOKEN_MISSING_ERROR: "Refresh token is required",
  SUCCESS_PASSWORD_CHANGE: "Password changed successfully",
  OLD_PASS_REQUIRED: "The old password field is required.",
  NEW_PASS_REQUIRED: "The new password field is required.",
  OLD_PASS_NOT_MATCH: "Old password does not match",
  USERNAME_SAME_ERROR: "username must be different from the current username",
  SUCCESS_PROFILE_UPDATE: "Profile updated successfully",
  SUCCESS_FEED_UPDATE: "Feed updated successfully",
  FEED_NOT_FOUND: "feed not found",
  COMMENT_NOT_FOUND: "Comment not found",
  SUCCESS_FEED_CREATE: "feed created successfully",
  FEED_LIKE: "feed liked",
  COMMENT_LIKE: "Comment liked",
  FEED_SAVED: "feed saved successfully",
  FEED_UNSAVED: " feed un saved successfully",
  FEED_DISLIKE: "feed un liked",
  COMMENT_DISLIKE: "Comment un liked",
  FEED_COMMENT_NOT_FOUND: "comment not found",
  FEED_COMMENT: "commented successfully",
  CHAT_NOT_FOUND: "Chat not found.",
};

// export module pool to be used in other files
module.exports = Object.freeze(constant);
